### PR TITLE
Fixed some typos in README.rst

### PR DESCRIPTION
**Pull request by ablondin**
Mostly RestructuredText reformatting.

### CODE REVIEW

**Comment by williamstein** [comment]
can you rebase this – it has conflicts.

**Comment by ablondin** [comment]
It seems my branch is already up-to-date with `master`. I don't see what is the problem...

**Comment by williamstein** [comment]
You’re right, and it looks good to me.  (Sorry, was reviewing this during a talk about this package, and got confused.)

**Comment by ablondin** [comment]
No problem :)

**Pull request merged**
