### PR TITLE
Add Travis CI scripts

### PR DESCRIPTION
**Pull request by mkoeppe**
Hi Nicolas,
I'd like to contribute Travis CI scripts for the sample project.
Included is also a fix for error signaling of "setup.py test".
Best wishes for the new year,
Matthias

### CODE REVIEW

**Comment by videlec** [comment]
I think that it would be better to clone the base projects and add the travis CI scripts in this clone. The base is intended to be used by somebody without knowledge of anything and should remain as simple as possible.

However, I think that a list of optional stuff in the README that point toward other projects would be very good!

**Comment by nthiery** [comment]
Hi Matthias, and happy new year too!
I really like that feature, and am going to use it for my own packages!

Just a suggestion: using directly pip commands, rather than going through the Makefile (e.g. `make install`). The latter is really just meant as shorthand for the user. Some even argued that we should remove it, as it's a (small) deviation to Python's standard packaging.

No strong opinion on whether to integrate this feature directly into sage-sample, or have a forked repository. I see Vincent's point. The sage-sample repo should anyway be moved to the sagemath organization, and it could make sense to have a collection of repos sage-sample, sage-sample-with-travis, ...

Cheers,

**Comment by mkoeppe** [comment]
Sure, please feel free to use this in any way you think is best.
Thanks for providing this sample structure -- I'm now using the part for building Sphinx documentation in my own project.

**Comment by nthiery** [comment]
Hi @videlec : after a discussion with Luca and Erik about a cookie cutter for Sage (see #5), I would tend to just merge this feature, and worry later about how to make it optional. What do you think?

**Comment by videlec** [comment]
cookie cutter would indeed be better than multiplying repositories!

**Comment by nthiery** [comment]
Ok, I merge then. Thanks Matthias for the contribution, and glad to hear `sage_sample` was helpful!

**Pull request merged**
